# Generated by Django 3.2.25 on 2024-08-06 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectsClosed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='عنوان پروژه')),
                ('ceo', models.CharField(max_length=300, verbose_name='کارفرما پروژه')),
                ('calendar', models.CharField(blank=True, max_length=300, verbose_name='تاریخ شروع پروژه')),
                ('category', models.CharField(blank=True, max_length=300, verbose_name='شماره قرارداد')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectsOpen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='عنوان پروژه')),
                ('ceo', models.CharField(max_length=300, verbose_name='کارفرما پروژه')),
                ('calendar', models.CharField(max_length=300, verbose_name='تاریخ شروع پروژه')),
                ('category', models.CharField(max_length=300, verbose_name='دسته بندی پروژه')),
                ('img_1', models.ImageField(upload_to='img-project-open', verbose_name='تصویر پروژه 1')),
                ('img_2', models.ImageField(blank=True, upload_to='img-project-open', verbose_name='تصویر پروژه 2')),
                ('img_3', models.ImageField(blank=True, upload_to='img-project-open', verbose_name='تصویر پروژه 3')),
                ('img_4', models.ImageField(blank=True, upload_to='img-project-open', verbose_name='تصویر پروژه 4')),
                ('img_5', models.ImageField(blank=True, upload_to='img-project-open', verbose_name='تصویر پروژه 5')),
                ('description_1', models.TextField(verbose_name='بند 1 توضیحات پروژه')),
                ('description_2', models.TextField(blank=True, verbose_name='بند 2 توضیحات پروژه')),
                ('description_3', models.TextField(blank=True, verbose_name='بند 3 توضیحات پروژه')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectsOpenMine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='عنوان پروژه')),
                ('ceo', models.CharField(max_length=300, verbose_name='مالکیت پروژه')),
                ('calendar', models.CharField(max_length=300, verbose_name='تاریخ شروع پروژه')),
                ('category', models.CharField(max_length=300, verbose_name='دسته بندی پروژه')),
                ('img_1', models.ImageField(upload_to='img-project-open', verbose_name='تصویر پروژه 1')),
                ('img_2', models.ImageField(blank=True, upload_to='img-project-open', verbose_name='تصویر پروژه 2')),
                ('img_3', models.ImageField(blank=True, upload_to='img-project-open', verbose_name='تصویر پروژه 3')),
                ('img_4', models.ImageField(blank=True, upload_to='img-project-open', verbose_name='تصویر پروژه 4')),
                ('img_5', models.ImageField(blank=True, upload_to='img-project-open', verbose_name='تصویر پروژه 5')),
                ('description_1', models.TextField(verbose_name='بند 1 توضیحات پروژه')),
                ('description_2', models.TextField(blank=True, verbose_name='بند 2 توضیحات پروژه')),
                ('description_3', models.TextField(blank=True, verbose_name='بند 3 توضیحات پروژه')),
            ],
        ),
    ]
