# Generated by Django 3.2.25 on 2024-08-06 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectsApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectsclosed',
            options={'verbose_name': 'پروژه ', 'verbose_name_plural': 'پروژه های به پایان رسیده'},
        ),
        migrations.AlterModelOptions(
            name='projectsopen',
            options={'verbose_name': 'پروژه ', 'verbose_name_plural': 'پروژه های درحال اجرا'},
        ),
        migrations.AlterModelOptions(
            name='projectsopenmine',
            options={'verbose_name': 'پروژه ', 'verbose_name_plural': 'پروژه های معدنی درحال اجرا'},
        ),
        migrations.AddField(
            model_name='projectsopen',
            name='slug',
            field=models.SlugField(null=True, verbose_name='عنوان در url'),
        ),
        migrations.AddField(
            model_name='projectsopenmine',
            name='slug',
            field=models.SlugField(null=True, verbose_name='عنوان در url'),
        ),
    ]
