# Generated by Django 3.2.25 on 2024-08-09 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectsApp', '0002_auto_20240806_1527'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectsopenmine',
            options={'verbose_name': 'پروژه', 'verbose_name_plural': 'پروژه های معدنی درحال اجرا'},
        ),
        migrations.AddField(
            model_name='projectsopen',
            name='boolean',
            field=models.BooleanField(default=False, null=True, verbose_name='در صفحه اصلی نمایش داده شود / نشود'),
        ),
    ]
