# Generated by Django 3.2.25 on 2025-03-11 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cooperate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cooperate',
            name='birth_cert_date',
            field=models.CharField(max_length=10, verbose_name='تاریخ صدور شناسنامه'),
        ),
        migrations.AlterField(
            model_name='cooperate',
            name='birth_date',
            field=models.CharField(max_length=10, verbose_name='تاریخ تولد'),
        ),
    ]
