# Generated by Django 3.2.25 on 2025-03-11 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cooperate', '0002_auto_20250311_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cooperate',
            name='birth_cert_date',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='تاریخ صدور شناسنامه'),
        ),
        migrations.AlterField(
            model_name='cooperate',
            name='birth_cert_image',
            field=models.ImageField(blank=True, null=True, upload_to='birth_certs/', verbose_name='تصویر شناسنامه'),
        ),
        migrations.AlterField(
            model_name='cooperate',
            name='birth_cert_page2_image',
            field=models.ImageField(blank=True, null=True, upload_to='birth_certs/', verbose_name='صفحه دوم شناسنامه'),
        ),
        migrations.AlterField(
            model_name='cooperate',
            name='birth_cert_page3_image',
            field=models.ImageField(blank=True, null=True, upload_to='birth_certs/', verbose_name='صفحه سوم شناسنامه'),
        ),
        migrations.AlterField(
            model_name='cooperate',
            name='birth_cert_page4_image',
            field=models.ImageField(blank=True, null=True, upload_to='birth_certs/', verbose_name='صفحه چهارم شناسنامه'),
        ),
        migrations.AlterField(
            model_name='cooperate',
            name='birth_cert_page5_image',
            field=models.ImageField(blank=True, null=True, upload_to='birth_certs/', verbose_name='صفحه پنجم شناسنامه'),
        ),
        migrations.AlterField(
            model_name='cooperate',
            name='birth_city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='شهر محل تولد'),
        ),
        migrations.AlterField(
            model_name='cooperate',
            name='birth_date',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='تاریخ تولد'),
        ),
        migrations.AlterField(
            model_name='cooperate',
            name='birth_number',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='شماره شناسنامه'),
        ),
        migrations.AlterField(
            model_name='cooperate',
            name='birth_province',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='استان محل تولد'),
        ),
        migrations.AlterField(
            model_name='cooperate',
            name='children_count',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='تعداد اولاد'),
        ),
        migrations.AlterField(
            model_name='cooperate',
            name='desired_job',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='عنوان شغل درخواستی'),
        ),
        migrations.AlterField(
            model_name='cooperate',
            name='desired_job_titles',
            field=models.TextField(blank=True, null=True, verbose_name='عناوین شغل\u200cهای درخواستی'),
        ),
        migrations.AlterField(
            model_name='cooperate',
            name='driving_license_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='نوع گواهینامه رانندگی'),
        ),
        migrations.AlterField(
            model_name='cooperate',
            name='education_level',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='مدرک تحصیلی'),
        ),
        migrations.AlterField(
            model_name='cooperate',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='cooperate',
            name='emergency_phone_number',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='شماره تلفن اضطراری'),
        ),
        migrations.AlterField(
            model_name='cooperate',
            name='employment_status',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='وضعیت اشتغال'),
        ),
        migrations.AlterField(
            model_name='cooperate',
            name='father_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='نام پدر'),
        ),
        migrations.AlterField(
            model_name='cooperate',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='cooperate',
            name='gender',
            field=models.CharField(blank=True, choices=[('مرد', 'مرد'), ('زن', 'زن'), ('', 'جنسیت')], max_length=10, null=True, verbose_name='جنسیت'),
        ),
        migrations.AlterField(
            model_name='cooperate',
            name='home_phone_number',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='شماره تلفن منزل'),
        ),
        migrations.AlterField(
            model_name='cooperate',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='cooperate',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('مجرد', 'مجرد'), ('متاهل', 'متاهل')], max_length=10, null=True, verbose_name='وضعیت تاهل'),
        ),
        migrations.AlterField(
            model_name='cooperate',
            name='mental_physical_status',
            field=models.TextField(blank=True, null=True, verbose_name='وضعیت روحی و جسمانی'),
        ),
        migrations.AlterField(
            model_name='cooperate',
            name='military_status',
            field=models.CharField(blank=True, choices=[('exempt', 'معافیت'), ('served', 'پایان خدمت')], max_length=20, null=True, verbose_name='وضعیت نظام وظیفه'),
        ),
        migrations.AlterField(
            model_name='cooperate',
            name='name_changed',
            field=models.CharField(blank=True, choices=[('', 'آیا نام و یا نام خانوادگی خود را تغیر داده اید؟'), ('بله', 'بله'), ('خیر', 'خیر')], max_length=10, null=True, verbose_name='تغییر نام'),
        ),
        migrations.AlterField(
            model_name='cooperate',
            name='national_card_back_image',
            field=models.ImageField(blank=True, null=True, upload_to='national_cards/', verbose_name='تصویر پشت کارت ملی'),
        ),
        migrations.AlterField(
            model_name='cooperate',
            name='national_card_image',
            field=models.ImageField(blank=True, null=True, upload_to='national_cards/', verbose_name='تصویر کارت ملی'),
        ),
        migrations.AlterField(
            model_name='cooperate',
            name='national_number',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='شماره ملی'),
        ),
        migrations.AlterField(
            model_name='cooperate',
            name='ok_no',
            field=models.BooleanField(blank=True, null=True, verbose_name='تایید کاربر برای استخدام'),
        ),
        migrations.AlterField(
            model_name='cooperate',
            name='phone_number',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='شماره تلفن همراه'),
        ),
        migrations.AlterField(
            model_name='cooperate',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/', verbose_name='عکس پرسنلی'),
        ),
        migrations.AlterField(
            model_name='cooperate',
            name='referral_source',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='طریقه آشنایی با شرکت'),
        ),
        migrations.AlterField(
            model_name='cooperate',
            name='requested_salary',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='حقوق درخواستی'),
        ),
        migrations.AlterField(
            model_name='cooperate',
            name='residence_address',
            field=models.TextField(blank=True, null=True, verbose_name='آدرس محل سکونت'),
        ),
        migrations.AlterField(
            model_name='cooperate',
            name='residence_city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='شهر سکونت'),
        ),
        migrations.AlterField(
            model_name='cooperate',
            name='residence_postcode',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='کد پستی محل سکونت'),
        ),
        migrations.AlterField(
            model_name='cooperate',
            name='residence_province',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='استان سکونت'),
        ),
        migrations.AlterField(
            model_name='cooperate',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/', verbose_name='رزومه'),
        ),
        migrations.AlterField(
            model_name='cooperate',
            name='step_1',
            field=models.BooleanField(blank=True, null=True, verbose_name='تکمیل مرحله اول'),
        ),
        migrations.AlterField(
            model_name='cooperate',
            name='step_2',
            field=models.BooleanField(blank=True, null=True, verbose_name='تکمیل مرحله دوم'),
        ),
        migrations.AlterField(
            model_name='cooperate',
            name='step_3',
            field=models.BooleanField(blank=True, null=True, verbose_name='تکمیل مرحله سوم'),
        ),
        migrations.AlterField(
            model_name='cooperate',
            name='step_4',
            field=models.BooleanField(blank=True, null=True, verbose_name='تکمیل مرحله چهارم'),
        ),
    ]
