# Generated by Django 3.2.25 on 2025-03-29 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cooperate', '0003_auto_20250311_2322'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cooperate',
            options={'verbose_name': 'درخواست استخدام', 'verbose_name_plural': 'درخواست های استخدام'},
        ),
        migrations.AlterField(
            model_name='cooperate',
            name='national_number',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='شماره ملی'),
        ),
    ]
