# Generated by Django 3.2.25 on 2025-03-29 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cooperate', '0004_auto_20250329_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cooperate',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='جنسیت'),
        ),
    ]
