# Generated by Django 3.2.25 on 2025-04-01 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cooperate', '0005_alter_cooperate_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='cooperate',
            name='residence_address_2',
            field=models.TextField(blank=True, null=True, verbose_name='آدرس دوم محل سکونت'),
        ),
        migrations.AddField(
            model_name='cooperate',
            name='residence_work',
            field=models.TextField(blank=True, null=True, verbose_name='آدرس محل کار'),
        ),
        migrations.AlterField(
            model_name='cooperate',
            name='birth_cert_image',
            field=models.ImageField(blank=True, null=True, upload_to='birth_certs-user-cooperate/', verbose_name='تصویر شناسنامه'),
        ),
        migrations.AlterField(
            model_name='cooperate',
            name='birth_cert_page2_image',
            field=models.ImageField(blank=True, null=True, upload_to='birth_certs-user-cooperate/', verbose_name='صفحه دوم شناسنامه'),
        ),
        migrations.AlterField(
            model_name='cooperate',
            name='birth_cert_page3_image',
            field=models.ImageField(blank=True, null=True, upload_to='birth_certs-user-cooperate/', verbose_name='صفحه سوم شناسنامه'),
        ),
        migrations.AlterField(
            model_name='cooperate',
            name='birth_cert_page4_image',
            field=models.ImageField(blank=True, null=True, upload_to='birth_certs-user-cooperate/', verbose_name='صفحه چهارم شناسنامه'),
        ),
        migrations.AlterField(
            model_name='cooperate',
            name='birth_cert_page5_image',
            field=models.ImageField(blank=True, null=True, upload_to='birth_certs-user-cooperate/', verbose_name='صفحه پنجم شناسنامه'),
        ),
        migrations.AlterField(
            model_name='cooperate',
            name='name_changed',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='وضعیت تغیر نام'),
        ),
        migrations.AlterField(
            model_name='cooperate',
            name='national_card_back_image',
            field=models.ImageField(blank=True, null=True, upload_to='national_cards-user-cooperate/', verbose_name='تصویر پشت کارت ملی'),
        ),
        migrations.AlterField(
            model_name='cooperate',
            name='national_card_image',
            field=models.ImageField(blank=True, null=True, upload_to='national_cards-user-cooperate/', verbose_name='تصویر کارت ملی'),
        ),
        migrations.AlterField(
            model_name='cooperate',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos-user-cooperate/', verbose_name='عکس پرسنلی'),
        ),
    ]
