# Generated by Django 3.2.25 on 2025-04-10 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cooperate', '0006_auto_20250401_0135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cooperate',
            name='marital_status',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='وضعیت تاهل'),
        ),
        migrations.AlterField(
            model_name='cooperate',
            name='military_service_end_date',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='تاریخ پایان خدمت'),
        ),
        migrations.AlterField(
            model_name='cooperate',
            name='military_service_start_date',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='تاریخ شروع خدمت'),
        ),
        migrations.AlterField(
            model_name='cooperate',
            name='military_status',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='وضعیت نظام وظیفه'),
        ),
    ]
