# Generated by Django 3.2.25 on 2025-04-10 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cooperate', '0007_auto_20250410_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cooperate',
            name='marriage_date',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='تاریخ ازدواج'),
        ),
    ]
