# Generated by Django 3.2.25 on 2025-04-10 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cooperate', '0008_alter_cooperate_marriage_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cooperate',
            name='children_count',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='تعداد اولاد'),
        ),
    ]
