# Generated by Django 3.2.25 on 2025-04-22 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cooperate', '0009_alter_cooperate_children_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cooperate',
            old_name='related_work_experience',
            new_name='descriptionـrelatedـwork',
        ),
        migrations.AddField(
            model_name='cooperate',
            name='relatedـworkـexperience',
            field=models.TextField(blank=True, null=True, verbose_name='وضعیت سابقه کار مرتبط با شرکت'),
        ),
    ]
