# Generated by Django 3.2.25 on 2025-05-05 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cooperate', '0010_auto_20250422_0416'),
    ]

    operations = [
        migrations.AddField(
            model_name='cooperate',
            name='driving_license_image2',
            field=models.ImageField(blank=True, null=True, upload_to='driving_licenses/', verbose_name='تصویر پشت گواهینامه'),
        ),
        migrations.AddField(
            model_name='cooperate',
            name='driving_motor',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='گواهینامه موتور'),
        ),
        migrations.AlterField(
            model_name='cooperate',
            name='relatedـworkـexperience',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='وضعیت سابقه کار مرتبط با شرکت'),
        ),
        migrations.AlterField(
            model_name='cooperate',
            name='special_license_code',
            field=models.TextField(blank=True, max_length=50, null=True, verbose_name='کد گواهینامه ویژه'),
        ),
    ]
