# Generated by Django 3.2.25 on 2025-05-06 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cooperate', '0011_auto_20250505_0300'),
    ]

    operations = [
        migrations.AddField(
            model_name='cooperate',
            name='has_special_license',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='وضعیت کد داشتن ویژه'),
        ),
    ]
