# Generated by Django 3.2.25 on 2025-05-06 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cooperate', '0012_cooperate_has_special_license'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cooperate',
            name='desired_job',
        ),
        migrations.AlterField(
            model_name='cooperate',
            name='has_special_license',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='وضعیت داشتن کد ویژه'),
        ),
        migrations.AlterField(
            model_name='cooperate',
            name='previous_work_experience',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='سابقه کار قبلی'),
        ),
    ]
