# Generated by Django 3.2.25 on 2024-08-04 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CeoSpeech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speech1', models.TextField(verbose_name='متن سخن مدیرعامل1')),
                ('speech2', models.TextField(verbose_name='متن سخن مدیرعامل2')),
                ('banner', models.ImageField(upload_to='image-ceo', verbose_name='تصویر مدیرعامل')),
            ],
            options={
                'verbose_name': 'سخن مدیرعامل',
            },
        ),
        migrations.CreateModel(
            name='ServiceWeb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='نام خدمت')),
                ('aboutUS2', models.TextField(verbose_name='متن توضیح خدمات')),
                ('aboutUS3', models.SlugField(verbose_name='عنوان در url')),
            ],
            options={
                'verbose_name': 'خدمات ما',
                'verbose_name_plural': 'خدمت',
            },
        ),
        migrations.CreateModel(
            name='SettingWeb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.ImageField(upload_to='image-banner', verbose_name='تصویر بنر')),
                ('aboutUS1', models.TextField(verbose_name='متن درباره ما1')),
                ('aboutUS2', models.TextField(verbose_name='متن درباره ما2')),
                ('aboutUS3', models.TextField(verbose_name='متن درباره ما3')),
                ('bannerUS1', models.ImageField(upload_to='image-about-us', verbose_name='تصویر درباره ما1')),
                ('bannerUS2', models.ImageField(upload_to='image-about-us', verbose_name='تصویر درباره ما2')),
                ('m1', models.CharField(max_length=300, verbose_name='سابقه شرکت')),
                ('m2', models.CharField(max_length=300, verbose_name='تعداد پروژه های تکمیل شده')),
                ('m3', models.CharField(max_length=300, verbose_name='تعداد مشتری')),
                ('m4', models.CharField(max_length=300, verbose_name='تعداد اعضای پرسنل')),
                ('banner2', models.ImageField(upload_to='image-banner', verbose_name='تصویر بخش چرا شرکت صدرا سازه')),
                ('ok_no', models.BooleanField(default=False, verbose_name='نمایش داده شود / نمایش داده نشود')),
            ],
            options={
                'verbose_name': 'تنظیمات',
                'verbose_name_plural': 'تنظیمات',
            },
        ),
        migrations.CreateModel(
            name='TeamCo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_pr', models.CharField(max_length=300, verbose_name='نام اعضای پرسنل')),
                ('img_pr', models.ImageField(upload_to='image-team', verbose_name='تصویر پرسنل')),
            ],
            options={
                'verbose_name': 'تیم ما',
                'verbose_name_plural': 'پرسنل',
            },
        ),
    ]
