# Generated by Django 3.2.25 on 2024-08-04 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogoCompani',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_co', models.CharField(max_length=300, verbose_name='نام شرکت کارفرما')),
                ('img_co', models.ImageField(upload_to='logo-compani', verbose_name='لوگو شرکت کارفرما')),
            ],
            options={
                'verbose_name': 'لوگو',
                'verbose_name_plural': 'ایجاد لوگو شرکت های کارفرما',
            },
        ),
        migrations.AlterModelOptions(
            name='ceospeech',
            options={'verbose_name': '', 'verbose_name_plural': 'بخش سخن مدیرعامل'},
        ),
    ]
