# Generated by Django 3.2.25 on 2024-08-05 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeApp', '0003_auto_20240805_0016'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serviceweb',
            options={'verbose_name': 'خدمات ', 'verbose_name_plural': 'خدمت ما'},
        ),
        migrations.AddField(
            model_name='serviceweb',
            name='banner',
            field=models.ImageField(blank=True, upload_to='image-service', verbose_name='تصویر خدمات'),
        ),
    ]
