# Generated by Django 3.2.25 on 2024-08-06 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeApp', '0004_auto_20240805_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ceospeech',
            name='speech2',
            field=models.TextField(blank=True, verbose_name='متن سخن مدیرعامل2'),
        ),
    ]
