# Generated by Django 3.2.25 on 2024-08-11 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeApp', '0005_alter_ceospeech_speech2'),
    ]

    operations = [
        migrations.CreateModel(
            name='TruckOne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='نوع مکانیزم')),
                ('number', models.IntegerField(verbose_name='تعداد')),
            ],
            options={
                'verbose_name': 'ماشین',
                'verbose_name_plural': 'تنظیمات ماشین آلات حمل',
            },
        ),
        migrations.CreateModel(
            name='TruckTow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='نوع مکانیزم')),
                ('number', models.IntegerField(verbose_name='تعداد')),
            ],
            options={
                'verbose_name': 'ماشین',
                'verbose_name_plural': 'تنظیمات ماشین آلات راهسازی',
            },
        ),
        migrations.CreateModel(
            name='TruckTree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='نوع مکانیزم')),
                ('number', models.IntegerField(verbose_name='تعداد')),
            ],
            options={
                'verbose_name': 'ماشین',
                'verbose_name_plural': 'تنظیمات ماشین آلات بارگیری',
            },
        ),
    ]
