# Generated by Django 3.2.25 on 2024-10-22 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeApp', '0006_truckone_trucktow_trucktree'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingweb',
            name='banner3',
            field=models.ImageField(blank=True, upload_to='image-banner', verbose_name='تصویر بنر3'),
        ),
    ]
