# Generated by Django 3.2.25 on 2024-10-22 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeApp', '0007_settingweb_banner3'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingweb',
            name='banner4',
            field=models.ImageField(blank=True, upload_to='image-banner', verbose_name='تصویر بنر2'),
        ),
    ]
